name: LasTools release
run-name: Release ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
      tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions: write-all

env:
  APP_VERSION: v1.0.0
  
jobs:
  build:
    strategy:
        matrix:
          os: [ubuntu-20.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: make
        run: make
      - name: Copy deps
        run: cp -a bin/ser* bin64/
      - name: Zip asset
        run: 7z a -tzip ./LasTools-${{matrix.os}}.zip ./bin/* '-xr!unit'
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: false
          name: Release ${{ github.ref }}
          files: |
            ./LasTools-${{matrix.os}}.zip