name: LasTools release

on:
  push:
      tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
  build:
    strategy:
        matrix:
          os: [ubuntu-18.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: make
        run: make
      - name: Copy deps
        run: cp -a bin/ser* bin64/
      - name: Zip asset
        run: 7z a -tzip ./LasTools-${{matrix.os}}.zip ./bin/* '-xr!unit'
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./LasTools-${{matrix.os}}.zip
          asset_name: LasTools-${{matrix.os}}.zip
          asset_content_type: application/zip
